# Generated by Django 5.0.6 on 2024-06-07 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_department_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meat',
            name='packaged',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
