# Generated by Django 5.0.6 on 2024-06-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_department_api', '0002_alter_meat_packaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meat',
            name='type',
            field=models.CharField(default='Meat', editable=False, max_length=32),
        ),
    ]
